apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: container-1

    command: ['sh', '-c', 'sleep 3600']

    volumeMounts:
    - mountPath: /demo1
      name: demo-volume

  - image: alpine
    imagePullPolicy: IfNotPresent
    name: container-2

    command: ['sh', '-c', 'sleep 3600']

    volumeMounts:
    - mountPath: /demo2
      name: demo-volume

  - image: alpine
    imagePullPolicy: IfNotPresent
    name: container-3

    command: ['sh', '-c', 'sleep 3600']

    volumeMounts:
    - mountPath: /demo3
      name: demo-volume

  volumes:
  - name: demo-volume
    emptyDir: {}
