apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-green
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app
        version: 2.0.0
    spec:
      containers:
        - name: demo-green
          image: gcr.io/mykubenatesproject/demogreen:green
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: 100Mi
