apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
    version: 2.0.0
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
